# Generated by Django 3.1.4 on 2020-12-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onesite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
