# Generated by Django 3.1.2 on 2020-12-01 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
