# Generated by Django 3.1.4 on 2020-12-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onesite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='foreign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=10)),
                ('count', models.PositiveIntegerField()),
            ],
        ),
    ]
