# Generated by Django 3.1.4 on 2020-12-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onesite', '0002_foreign'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('week', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=3)),
                ('gender', models.CharField(max_length=1)),
                ('imported', models.CharField(max_length=1)),
                ('age', models.CharField(max_length=10)),
                ('count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='monthcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='weekcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField()),
            ],
        ),
    ]
