# Generated by Django 3.1.4 on 2020-12-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onesite', '0003_info_monthcase_weekcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
